apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-api
  annotations:
    domainName: "apicharts.lifesizecloudbeta.com"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    dns: route53
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.externalPort }}
    targetPort: {{ .Values.api.service.internalPort }}
    protocol: TCP
    name: {{ .Values.api.service.name }}
  selector:
    app: {{ template "fullname" . }}-api
